Don't overwrite files
lamby/django-filebased-email-backend-ng pull request #3
Opened 2018-02-07 15:57 UTC by David-Guillot

I sometimes need to call `send_mail` multiple times to send different emails to different users, and i want to debug all emails at once. I think the easiest way to achieve this is to avoid deleting the whole folder and timestamp subfolders instead of iterating the name.

2018-02-08 08:04 UTC, lamby commented
I actually somewhat think is a feature that we overwrite, at least by defualt. How about we make ``settings.EMAIL_FILE_PATH`` templatatable? ie. we will interpolate the current timestamp.

2018-02-23 14:54 UTC, David-Guillot commented
I understand your point but my use case implies sending multiple different emails in a loop, each iteration calling `send_mail` since the email HTML attachment is different.

Maybe the best way to deal with this situation would be to keep the `rmtree` but to create a subtree with one folder per distinct email, maybe discriminated by recipient email instead of timestamps. I'll push a second commit (that would fixup the first one) implementing this idea.

Thanks for your feedback!

2018-02-23 15:07 UTC, lamby commented
Looking forward to seeing that; I will have a proper look/think then. Do feel free to force-push here so that the eventual history is cleaner...

2018-02-23 16:52 UTC, David-Guillot commented
Okay @lamby i have pushed a solution. It might seem a bit overkill but i used inspection to aggregate folders by usage. Thus i can achieve the following use cases:

* The previously existing use case (overwriting folders at each `send_mail()` call): done by deleting every folder except the one of the current aggregation
* My use case (a feature calling `send_mail()` multiple times): done by calculating a unique name of a folder that will contain 1 sub-folder per email sent (sub-folder named after the recipient)

Let me know what you think about it ;)

2018-02-23 21:53 UTC, lamby requested changes
* Can you zip up (or paste output of `tree`) some example output?
* Also, does this change the default behaviour?

2018-02-23 21:53 UTC, lamby commented on django_filebased_email_backend_ng/backend.py
> +            inspect.getouterframes(inspect.currentframe())
I really dislike ``inspect`` I'm afraid..

2018-02-23 21:53 UTC, lamby commented on django_filebased_email_backend_ng/backend.py
> +            message_dir = '__'.join(message.to).replace('@', '_AT_')
There are surely other characters that would need replacing. (Why don't we whitelist instead of blacklist?)

2020-09-07 07:52 UTC, David-Guillot commented
After 2 years I never found time to work on this, so I'm closing it.

2020-09-07 07:52 UTC, closed without merging